version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_APP_USER_API_URL=${VITE_APP_USER_API_URL}
      - VITE_APP_PLANS_API_URL=${VITE_APP_PLANS_API_URL}
      - VITE_APP_AUTH_API_URL=${VITE_APP_AUTH_API_URL}
      - VITE_APP_USER_PLAN_API_URL=${VITE_APP_USER_PLAN_API_URL}
      - VITE_APP_BILL_API_URL=${VITE_APP_BILL_API_URL}